/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newdeletequerytestproject.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.newdeletequerytestproject.Table106;

/**
 * Service object for domain model class {@link Table106}.
 */
public interface Table106Service {

    /**
     * Creates a new Table106. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table106 if any.
     *
     * @param table106 Details of the Table106 to be created; value cannot be null.
     * @return The newly created Table106.
     */
	Table106 create(@Valid Table106 table106);


	/**
	 * Returns Table106 by given id if exists.
	 *
	 * @param table106Id The id of the Table106 to get; value cannot be null.
	 * @return Table106 associated with the given table106Id.
     * @throws EntityNotFoundException If no Table106 is found.
	 */
	Table106 getById(String table106Id) throws EntityNotFoundException;

    /**
	 * Find and return the Table106 by given id if exists, returns null otherwise.
	 *
	 * @param table106Id The id of the Table106 to get; value cannot be null.
	 * @return Table106 associated with the given table106Id.
	 */
	Table106 findById(String table106Id);


	/**
	 * Updates the details of an existing Table106. It replaces all fields of the existing Table106 with the given table106.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Table106 if any.
     *
	 * @param table106 The details of the Table106 to be updated; value cannot be null.
	 * @return The updated Table106.
	 * @throws EntityNotFoundException if no Table106 is found with given input.
	 */
	Table106 update(@Valid Table106 table106) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table106 with the given id.
	 *
	 * @param table106Id The id of the Table106 to be deleted; value cannot be null.
	 * @return The deleted Table106.
	 * @throws EntityNotFoundException if no Table106 found with the given id.
	 */
	Table106 delete(String table106Id) throws EntityNotFoundException;

	/**
	 * Find all Table106s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table106s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Table106> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Table106s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table106s.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Table106> findAll(String query, Pageable pageable);

    /**
	 * Exports all Table106s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table106s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Table106.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

