/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newdeletequerytestproject;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table106 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE106`")
public class Table106 implements Serializable {

    private String id;

    @Id
    @Column(name = "`ID`", nullable = false, length = 1)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table106)) return false;
        final Table106 table106 = (Table106) o;
        return Objects.equals(getId(), table106.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

