/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newdeletequerytestproject.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.newdeletequerytestproject.Table16;
import com.newdeletequerytestproject.Table16Id;

/**
 * Service object for domain model class {@link Table16}.
 */
public interface Table16Service {

    /**
     * Creates a new Table16. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table16 if any.
     *
     * @param table16 Details of the Table16 to be created; value cannot be null.
     * @return The newly created Table16.
     */
	Table16 create(@Valid Table16 table16);


	/**
	 * Returns Table16 by given id if exists.
	 *
	 * @param table16Id The id of the Table16 to get; value cannot be null.
	 * @return Table16 associated with the given table16Id.
     * @throws EntityNotFoundException If no Table16 is found.
	 */
	Table16 getById(Table16Id table16Id) throws EntityNotFoundException;

    /**
	 * Find and return the Table16 by given id if exists, returns null otherwise.
	 *
	 * @param table16Id The id of the Table16 to get; value cannot be null.
	 * @return Table16 associated with the given table16Id.
	 */
	Table16 findById(Table16Id table16Id);


	/**
	 * Updates the details of an existing Table16. It replaces all fields of the existing Table16 with the given table16.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Table16 if any.
     *
	 * @param table16 The details of the Table16 to be updated; value cannot be null.
	 * @return The updated Table16.
	 * @throws EntityNotFoundException if no Table16 is found with given input.
	 */
	Table16 update(@Valid Table16 table16) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table16 with the given id.
	 *
	 * @param table16Id The id of the Table16 to be deleted; value cannot be null.
	 * @return The deleted Table16.
	 * @throws EntityNotFoundException if no Table16 found with the given id.
	 */
	Table16 delete(Table16Id table16Id) throws EntityNotFoundException;

	/**
	 * Find all Table16s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table16s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Table16> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Table16s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table16s.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Table16> findAll(String query, Pageable pageable);

    /**
	 * Exports all Table16s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table16s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Table16.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

